// this file is automatically generated by git.version.ts script
export const versions = {
      version: '0.0.1',
      commitId: 'dcf1dfdffd1c0121fedf0413ae075c3b0040370c',
      branch: 'main',
      buildDate: '2024-05-23T11:08:48.519Z'
  };
  